name = "RMLImaging"
uuid = "4d23c25a-f84e-4dc0-9513-4942a305df7e"
authors = ["Kazunori Akiyama"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
